"""empty message

<<<<<<<< HEAD:migrations/versions/4e846f41f700_.py
Revision ID: 4e846f41f700
Revises: 
Create Date: 2025-06-19 16:31:37.147772
========
Revision ID: 51583c54aa20
Revises: 
Create Date: 2025-06-20 22:08:41.959678
>>>>>>>> develop:migrations/versions/51583c54aa20_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/4e846f41f700_.py
revision = '4e846f41f700'
========
revision = '51583c54aa20'
>>>>>>>> develop:migrations/versions/51583c54aa20_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('salt', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('comment')
    # ### end Alembic commands ###
